#pragma once

#define CWM_SYS_UPDATE_TRACE			WM_USER + 0x0000

#define CWM_SYS_CHANGE_STATUS			WM_USER + 0x1000

#define CWM_SYS_CHANGE_PLC_STAUS		WM_USER + 0x1500
//SystemMode
#define CWM_SYS_CHANGE_MODE				WM_USER + 0x2000

//SystemLED
#define CWM_SYS_CHANGE_LED				WM_USER + 0x3000

//System Data Updata
#define CWM_SYS_UPDATE_LANG				WM_USER + 0x4000
#define CWM_SYS_UPDATE_RECIPEID			WM_USER + 0x4001
#define CWM_SYS_UPDATE_SYSTEMID			WM_USER + 0x4002
#define CWM_SYS_UPDATE_PRODUCT_COUNT	WM_USER + 0x4003
#define CWM_SYS_UPDATE_CHAMBER_STATUS	WM_USER + 0x4004

#define CWM_SYS_UPDATE_PRCESS_STATUS_ROBOT		WM_USER + 0x4005
#define CWM_SYS_UPDATE_PRCESS_STATUS_CV			WM_USER + 0x4006
#define CWM_SYS_UPDATE_PRCESS_STATUS_PCB_PRESS	WM_USER + 0x4007

#define CWM_SYS_UPDATE_PRCESS_STATUS_EXIST_ROBOT		WM_USER + 0x4008
#define CWM_SYS_UPDATE_PRCESS_STATUS_EXIST_CV			WM_USER + 0x4009
#define CWM_SYS_UPDATE_PRCESS_STATUS_EXIST_STICKER		WM_USER + 0x400A

#define CWM_SYS_UPDATE_PRCESS_STATUS_CV_IN				WM_USER + 0x400B
#define CWM_SYS_UPDATE_PRCESS_STATUS_PP_REQ				WM_USER + 0x400C
#define CWM_SYS_UPDATE_PRCESS_STATUS_PP_SAFE			WM_USER + 0x400D

#define CWM_SHOW_WINDOW			WM_USER + 0x9000
#define CWM_ADD_POINT			WM_USER + 0x9001
#define CWM_DELETE_POINT		WM_USER + 0x9002
#define CWM_INSERT_POINT		WM_USER + 0x9003
#define CWM_SAVE_POINT			WM_USER + 0x9004
#define CWM_WRITE_POINT			WM_USER + 0x9005
#define CWM_MOVE_POINT			WM_USER + 0x9006
#define CWM_UPDATE_RECIPE		WM_USER + 0x9007

#define CWM_PARAMLIST_CBN_SELECTCHANGE		WM_USER + 0x9008